version: 2

registries:
  maven-github:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: POSTMAN
    password: PAT

updates:

- package-ecosystem: github-actions
  directory: /
  schedule:
     interval: daily

- package-ecosystem: gradle
  directory: /
  cooldown:
    default-days: 3
    exclude:
      - "no.nav.aap.*"
  schedule:
    interval: daily
  registries:
    - maven-github

- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
