apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: innsending
  namespace: aap
  labels:
    team: aap
    sub: innsending
spec:
  image: {{image}}
  leaderElection: true
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 2
    min: 2
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 2048Mi
  accessPolicy:
    inbound:
      rules:
        - application: innsyn
        - application: soknad
        - application: tms-utkast
          namespace: min-side
          cluster: prod-gcp
    outbound:
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
      rules:
        - application: pdfgen
        - application: oppslag
        - application: clamav
          namespace: nais-system
  redis:
    - instance: mellomlager
      access: readwrite
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: innsending
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  env:
    - name: JOARK_BASE_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: JOARK_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: OPPSLAG_SCOPE
      value: api://prod-gcp.aap.oppslag/.default
