apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: innsending
  namespace: aap
  labels:
    team: aap
    sub: innsending
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
spec:
  image: {{image}}
  ingresses:
    - https://aap-innsending.intern.dev.nav.no
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: innsyn
        - application: soknad
        - application: min-side-microfrontend
        - application: tms-utkast
          namespace: min-side
          cluster: dev-gcp
    outbound:
      external:
        - host: dokarkiv.dev-fss-pub.nais.io
      rules:
        - application: pdfgen
        - application: oppslag
        - application: clamav
          namespace: nais-system
  redis:
    - instance: mellomlager
      access: readwrite
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: innsending
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    tracing:
      enabled: true
  secureLogs:
    enabled: true
  env:
    - name: JOARK_BASE_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: JOARK_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: OPPSLAG_SCOPE
      value: api://dev-gcp.aap.oppslag/.default
