apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: aap-innsending
    team: aap
  name: valkey-aap-mellomlager
  namespace: aap
spec:
  plan: business-4
  project: nav-prod
  userConfig:
    valkey_persistence: "off"
---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: aap
  name: valkey-aap-mellomlager
  namespace: aap
spec:
  project: nav-prod
  integrationType: prometheus
  destinationEndpointId: 76685598-1048-4f56-b34a-9769ef747a92
  sourceServiceName: valkey-aap-mellomlager
