apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: innsending.v1
  namespace: aap
  labels:
    team: aap
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "{{kafka.permanent-delete-topics}}"
    kafka.format: json
    kafka.state: "false"
    github.url: https://github.com/navikt/aap-innsending
spec:
  pool: {{kafka.pool}}
  config:
    cleanupPolicy: compact,delete
    partitions: 12
    retentionHours: 168
  acl:
    - team: aap
      application: innsending
      access: readwrite