redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  pwd: ${REDIS_PASSWORD}
azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientId: ${AZURE_APP_CLIENT_ID}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}
fillager:
  baseUrl: ${FILLAGER_BASE_URL}
database:
  url: jdbc:postgresql://${NAIS_DATABASE_INNSENDING_INNSENDING_HOST}:${NAIS_DATABASE_INNSENDING_INNSENDING_PORT}/${NAIS_DATABASE_INNSENDING_INNSENDING_DATABASE}
  username: ${NAIS_DATABASE_INNSENDING_INNSENDING_USERNAME}
  password: ${NAIS_DATABASE_INNSENDING_INNSENDING_PASSWORD}