redis:
  host: ${REDIS_URI_MELLOMLAGER}
  port: ${REDIS_USERNAME_MELLOMLAGER}
  pwd: ${REDIS_PASSWORD_MELLOMLAGER}

azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientId: ${AZURE_APP_CLIENT_ID}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}

database:
  url: jdbc:postgresql://${NAIS_DATABASE_INNSENDING_INNSENDING_HOST}:${NAIS_DATABASE_INNSENDING_INNSENDING_PORT}/${NAIS_DATABASE_INNSENDING_INNSENDING_DATABASE}
  username: ${NAIS_DATABASE_INNSENDING_INNSENDING_USERNAME}
  password: ${NAIS_DATABASE_INNSENDING_INNSENDING_PASSWORD}