name: deploy branch http

on:
  push:
    branches: [ http ]
    paths-ignore:
      - '.nais/redis-dev.yml'
      - '.nais/redis-prod.yml'
      - '.github/**'
      - 'FUNKSJONELL.md'

jobs:
  gradle:
    permissions:
      contents: write
      actions: read
      checks: write
      id-token: write
    uses: navikt/aap-workflows/.github/workflows/gradle-build.yml@main
    secrets: inherit

  dev:
    permissions:
      contents: read
      id-token: write
    needs: gradle
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/application-dev.yml