name: publish documentation

on:
  push:
    branches:
      - main
    paths:
      - 'FUNKSJONELL.md'
      - '.github/workflows/docs.yml'

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: innsending
          sparse-checkout: |
            FUNKSJONELL.md

      - uses: actions/checkout@v5
        with:
          repository: navikt/aap-intern-sysdok
          ref: refs/heads/main
          path: sysdoc

      - name: create pull-request
        run: |
          cd sysdoc
          git checkout -b docs/innsending-${{ github.sha }}
          cp ../innsending/FUNKSJONELL.md dokumentasjon/docs/mine_aap/.
          gh pr create \
            --title "Update FUNKSJONELL.md" \
            --repo https://github.com/navikt/aap-intern-sysdok
