name: Redis

on:
  push:
    branches: [ main ]
    paths:
      - '.nais/redis-dev.yml'
      - '.nais/redis-prod.yml'

jobs:
  dev:
    permissions:
      contents: read
      id-token: write
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/redis-dev.yml

  prod:
    needs: dev
    permissions:
      contents: read
      id-token: write
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: prod-gcp
      manifest: .nais/redis-prod.yml

