name: Salsa

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    permissions:
      contents: read
      actions: read
      checks: write
      id-token: write
    uses: navikt/aap-workflows/.github/workflows/salsa.yml@main
    secrets: inherit
